.\" Copyright 2021 Matthew James Kraai
.\"
.\" This file is part of odo.
.\"
.\" odo is free software: you can redistribute it and/or modify it under
 \" the terms of the GNU Affero General Public License as published by the
 \" Free Software Foundation, either version 3 of the License, or (at your
 \" option) any later version.
.\"
.\" odo is distributed in the hope that it will be useful, but WITHOUT ANY
 \" WARRANTY; without even the implied warranty of MERCHANTABILITY or
 \" FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
 \" License for more details.
.\"
.\" You should have received a copy of the GNU Affero General Public
 \" License along with odo.  If not, see <https://www.gnu.org/licenses/>.

.TH ODO 1 2021-05-11 ftbfs.org
.SH NAME
odo \- help get things done
.SH SYNOPSIS
.nf
.B odo action add \fIdescription\fR ...
.B odo action ls
.B odo action rm \fIdescription\fR ...
.B odo action set description \fIold-description\fP \fInew-description\fR ...
.B odo goal add \fIdescription\fR ...
.B odo goal clear action \fIdescription\fR ...
.B odo goal ls
.B odo goal rm \fIdescription\fR ...
.B odo goal set action \fIdescription\fP \fIaction\fR ...
.B odo goal set description \fIold-description\fP \fInew-description\fR ...
.fi
.SH DESCRIPTION
The
.B odo
command helps get things done.
